url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "QuinnDACollins.github.io" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

