url: 'http://quinn.cafe'
#baseurl: 'QuinnDACollins.github.io'
title: "quinn's cafe" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss-v2

postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js