url: 'http://quinn.cafe'
baseurl: 'QuinnDACollins.github.io '
title: "quinn's cafe" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]